
# Configuraci\u00f3n del Servidor de Sockets
socket.host=127.0.0.1
socket.port=5000

# Configuraci\u00f3n de Base de Datos
db.url=jdbc:mysql://mysql-11b2f5ad-db-so.g.aivencloud.com:28915/auditorio?sslMode=REQUIRED
db.user=avnadmin
db.password=AVNS_BbW0UnDbv72t2jXued-

# Configuraci\u00f3n del Servidor Web
server.public.ip=127.0.0.1
server.public.port=8080