
# Configuraci\u00f3n del Servidor de Sockets
socket.host=127.0.0.1
socket.port=5000

# Configuraci\u00f3n de Base de Datos
db.url=jdbc:mysql://172.16.9.42:3306/auditorio?sslMode=REQUIRED
db.user=appuser
db.password=SistemasOperativos26!

# Configuraci\u00f3n del Servidor Web
server.public.ip=127.0.0.1
server.public.port=8080